name: Deploy to Github Pages

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - develop

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: action/checkout@v4

      - name: Install Node versions
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
